---
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost/task-manager
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update